main: xyz.Christopher.SuuCampus.Main
name: SuuCampus
version: 1.42
author: Christopher Newton
description: A plugin that allows you to tour Southern Utah University Campus virtually
commands:
  walk:
    description: Allows you to set up a path to a set of coordinates.
    usage: /walk [x coordinate] [y coordinate] [z coordinate] [moving enabled T/F]
    permission: SuuCampus.walk
    permission-message: You need the SuuCampus.walk permission in order to use this command.
  waypointwalk:
    description: Allows you to set a path to a previously created waypoint, works along with the command Waypoint
    usage: /walk [name of waypoint] [moving enabled T/F]
    permission: SuuCampus.waypointwalk
    permission-message: You need the SuuCampus.waypointwalk permission in order to use this command.
  campuswalk:
    description: Allows you to set up a path around an array of waypoints, to simulate a tour of an area.
    usage: /campuswalk <set of waypoints to concurrently walk to> [moving enabled T/F]
    permission: SuuCampus.campuswalk
    permission-message: You need the SuuCampus.campuswalk permission in order to use this command.
  listwaypoints:
    description: Allows you to view names of already created waypoints
    usage: /listwaypoints
    permission: SuuCampus.listwaypoints
    permission-message: You need the SuuCampus.listwaypoints permission in order to use this command
  setwaypoint:
    description: Allows you to set a waypoint for a specific (x,y,z) coordinate in the minecraft world that can be used later
    usage: /setwaypoint [name of new waypoint] [x coordinate] [y coordinate] [z coordinate] 
    permission: SuuCampus.setwaypoint
    permission-message: You need the SuuCampus.setwaypoint permission in order to use this command
  delwaypoint:
    description: Allows you to delete a waypoint that has already been set
    usage: /delwaypoint [name of waypoint to be deleted]
    permission: SuuCampus.delwaypoint
    permission-message: You need the SuuCampus.delwaypoint permission in order to use this command
  goto:
    description: Allows you to teleport to a waypoint that has already been set
    usage: /goto [name of waypoint to be teleported to]
    permission: SuuCampus.goto
    permission-message: You need the SuuCampus.goto permission in order to use this command
  connected:
    description: Development tool to test if the database is working correctly
    usage: /connected
    permission: SuuCampus.connection
    permission-message: You need the SuuCampus.connection permission in order to use this command
  createholo:
    description: Places a hologram where you stand with the department info from the database with the department that you choose
    usage: /createholo <department name>
    permission: SuuCampus.createholo
    permission-message: You need the SuuCampus.createholo permission in order to use this command
  adddeptinfo:
    description: Adds a department name, related information, and a video link to that department into the database
    usage: /adddeptinfo <name> <information> <video link>
    permission: SuuCampus.adddeptinfo
    permission-message: You need the SuuCampus.adddeptinfo permission in order to use this command
  listdepartments:
    description: Returns all department names
    usage: /listdepartments
    permission: SuuCampus.listdepartments
    permission-message: You need the SuuCampus.listdepartments permission in order to use this command
  deptinfo:
    description: Returns information from the specified department
    usage: /deptinfo <department>
    permission: SuuCampus.deptinfo
    permission-message: You need the SuuCampus.deptinfo permission in order to use this command
  deptvideo:
    description: Returns the video from the specified department
    usage: /deptvideo <department>
    permission: SuuCampus.deptvideo
    permission-message: You need the SuuCampus.deptvideo permission in order to use this command
  addclassroominfo:
    description: Adds a classroom with a room number, Building name, and a zoom link into the database
    usage: /addclassroominfo <Room Number> <Building Name> <Zoom Link>
    permission: SuuCampus.addclassroominfo
    permission-message: You need the SuuCampus.addclassroominfo permission in order to use this command
  editclasszoom:
    description: Updates a classrooms zoom link
    usage: /editclasszoom <Room Number> <Building Name> <New Zoom Link>
    permission: SuuCampus.editclasszoom
    permission-message: You need the SuuCampus.editclasszoom permission in order to use this command
  getzoom:
    description: Returns a zoom link
    usage: /getzoom <Room Number> <Building Name>
    permission: SuuCampus.getzoom
    permission-message: You need the SuuCampus.getzoom permission in order to use this command
  getclassrooms:
    description: Returns all classrooms
    usage: /getclassrooms
    permission: SuuCampus.getclassrooms
    permission-message: You need the SuuCampus.getclassrooms permission in order to use this command
  profemail:
    description: opens a gmail window, starts an email, and fills out the recipient field with the respective professors email
    usage: /profemail <First Name> <Last Name>
    permission: SuuCampus.profemail
    permission-message: You need the SuuCampus.profemail permission in order to use this command
  email:
    description: opens a gmail window, starts an email, and fills out the recipient field
    usage: /email <email>
    permission: SuuCampus.email
    permission-message: You need the SuuCampus.email permission in order to use this command
  addprofinfo:
    description: Adds a professors information into the database
    usage: /addprofinfo <first name> <last name> <email> <room> <department>
    permission: SuuCampus.addprofinfo
    permission-message: You need the SuuCampus.addprofinfo permission in order to use this command
  getprofemail:
    description: Returns a professors email
    usage: /getprofemail <first name> <last name>
    permission: SuuCampus.getprofemail
    permission-message: You need the SuuCampus.getprofemail permission in order to use this command
  getprofdept:
    description: Returns a professors department
    usage: /getprofdept <first name> <last name>
    permission: SuuCampus.getprofdept
    permission-message: You need the SuuCampus.getprofdept permission in order to use this command
  getprofroom:
    description: Returns a professors room number
    usage: /getprofroom
    permission: SuuCampus.getprofroom
    permission-message: You need the SuuCampus.getprofroom permission in order to use this command
  listprofessors:
    description: Returns all professors
    usage: /listprofessors
    permission: SuuCampus.listprofessors
    permission-message: You need the SuuCampus.listprofessors permission in order to use this command
  listdeptprofessors:
    description: Returns all professors from a specific department
    usage: /listdeptprofessors <department>
    permission: SuuCampus.listdeptprofessors
    permission-message: You need the SuuCampus.listdeptprofessors permission in order to use this command
      
permissions:
   